// SPDX-License-Identifier: UNLICENSED
// This file was autogenerated by running `kontrol load-state-diff`. Do not edit this file manually.

pragma solidity ^0.8.13;

import {Vm} from "forge-std/Vm.sol";

import {SetupSummary} from "./SetupSummary.sol";

// contract KontrolUtils is SetupSummary {
contract KontrolUtils is SetupSummary {
    // Cheat code address, 0x7109709ECfa91a80626fF3989D68f67F5b1DD12D
    Vm internal constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    function _notBuiltInAddress(address addr) internal view {
        vm.assume(addr != address(vm));
        vm.assume(addr != address(this));
        vm.assume(addr != address(poolManagerAddress));
        vm.assume(addr != address(currency0Address));
        vm.assume(addr != address(currency1Address));
    }
}